# The cluster name
#cluster.name: elasticsearch

# Path Settings
#path.conf: /path/to/conf
#path.data: /path/to/data
#path.work: /path/to/work
#path.logs: /path/to/logs
#path.plugins: /path/to/plugins

# Force all memory to be locked, forcing the JVM to never swap
#   When setting it, make sure ES_MIN_MEM and ES_MAX_MEM are set to the same value
#   and that the machine has enough memory to allocate.
#bootstrap.mlockall: true

# Gateway Settings
#   Controls when to start the initial recovery process when starting a new cluster
#   allowing for better reused of existing data during recovery.
#gateway.recover_after_nodes: 1
#gateway.recover_after_time: 5m
#gateway.expected_nodes: 2

# Recovery Throttling
#   The number of concurrent recoveries happening on a node
#cluster.routing.allocation.node_initial_primaries_recoveries: 4
#cluster.routing.allocation.node_concurrent_recoveries: 2
#   Peer shard recovery size based throttling (set to 100mb for example to enable)
#indices.recovery.max_size_per_sec: 0
#   Number open concurrent recovery streams allows
#indices.recovery.concurrent_streams: 5

# Controls the minimum number of master eligible nodes this node should "see"
# in order to operate within the cluster.
#   Set this to a higher value (2-4) when running more than 2 nodes in the cluster
#discovery.zen.minimum_master_nodes: 1

# The time to wait for ping responses from other nodes when doing node discovery
#discovery.zen.ping.timeout: 3s

# Unicast Discovery (disable multicast)
#discovery.zen.ping.multicast.enabled: false
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
