logstash:
  cluster:
    - manage_index_templates
  indices:
    - names: 'logstash-*'
      privileges:
        - write
        - read
        - create_index

# Marvel user role. Assign to marvel users.
monitoring_user:
  indices:
    - names:
        - '.marvel-es-*'
        - '.monitoring-*'
      privileges: [ "read" ]
    - names: '.kibana'
      privileges:
        - view_index_metadata
        - read

# Marvel remote agent role. Assign to the agent user on the remote marvel cluster
# to which the marvel agent will export all its data
remote_monitoring_agent:
  cluster: [ "manage_index_templates", "monitor" ]
  indices:
    - names:
        - '.marvel-es-*'
        - '.monitoring-*'
      privileges: [ "all" ]
